ALTER TABLE leads ADD COLUMN phone TEXT;
ALTER TABLE leads ADD COLUMN title TEXT;
ALTER TABLE leads ADD COLUMN website TEXT;
ALTER TABLE leads ADD COLUMN linkedin TEXT;
ALTER TABLE leads ADD COLUMN address TEXT;
ALTER TABLE leads ADD COLUMN country TEXT;
ALTER TABLE leads ADD COLUMN sheet_row INTEGER;
